import type { Metadata } from "next";
import Link from "next/link";
import SiteLayout from "@/components/site/SiteLayout";
import { Button } from "@/components/ui/button";
import { ArrowRight, FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Sample Report — WinterVell",
  description:
    "View a sample website audit report generated by WinterVell. Branded, structured, and evidence-based.",
};

const REPORT_SECTIONS = [
  {
    title: "Executive summary",
    content:
      "Overall score of 64/100. The website has notable issues in SEO foundations, meta descriptions, and heading structure. Technical health and performance are acceptable.",
  },
  {
    title: "Technical Health",
    score: 72,
    findings: 5,
    status: "Review",
  },
  {
    title: "SEO Foundations",
    score: 54,
    findings: 8,
    status: "Review",
  },
  {
    title: "Performance",
    score: 81,
    findings: 3,
    status: "Approved",
  },
  {
    title: "Mobile Experience",
    score: 75,
    findings: 4,
    status: "Review",
  },
  {
    title: "Accessibility Indicators",
    score: 48,
    findings: 9,
    status: "Review",
  },
  {
    title: "Conversion Clarity",
    score: 60,
    findings: 6,
    status: "Approved",
  },
  {
    title: "Trust Signals",
    score: 70,
    findings: 4,
    status: "Review",
  },
  {
    title: "Content Structure",
    score: 62,
    findings: 5,
    status: "Review",
  },
  {
    title: "AI-Search Readiness",
    score: 45,
    findings: 7,
    status: "Review",
  },
];

const SAMPLE_FINDINGS = [
  {
    title: "Missing meta descriptions",
    severity: "High",
    category: "SEO Foundations",
    evidence: "12 pages are missing <meta name='description'> tags.",
    impact: "Affects search engine indexing and click-through rates.",
  },
  {
    title: "Heading hierarchy broken",
    severity: "Medium",
    category: "Content Structure",
    evidence: "H3 elements appear before H2 elements on 4 pages.",
    impact: "Confuses screen readers and search engine crawlers.",
  },
  {
    title: "No structured data (JSON-LD)",
    severity: "Medium",
    category: "AI-Search Readiness",
    evidence: "No JSON-LD structured data found on any page.",
    impact: "Reduces visibility in AI-powered search results.",
  },
  {
    title: "Large layout shifts (CLS)",
    severity: "Low",
    category: "Performance",
    evidence: "CLS score of 0.18 on the homepage (target: < 0.1).",
    impact: "Causes visual instability during page load.",
  },
];

export default function SampleReportPage() {
  return (
    <SiteLayout>
      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <div className="flex items-center gap-2">
            <FileText className="size-5 text-primary" />
            <span className="text-label text-muted-foreground">
              Sample report
            </span>
          </div>
          <h1 className="mt-2 text-h1 sm:text-display text-foreground">
            Website Audit Report
          </h1>
          <p className="mt-4 text-body text-muted-foreground leading-relaxed">
            This is a sample report generated by WinterVell using fictional
            data. It demonstrates the report structure, evidence format, and
            category scoring.
          </p>
          <p className="mt-2 text-xs text-[var(--text-tertiary)]">
            Prepared by Northstar Digital · Fictional data · Meridian Health
            Group
          </p>
        </div>

        {/* Executive summary */}
        <section className="mt-12">
          <div className="rounded-lg border border-border bg-card p-6 shadow-xs">
            <h2 className="text-h4 text-foreground">Executive summary</h2>
            <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
              Overall score of 64/100. The website has notable issues in SEO
              foundations, meta descriptions, and heading structure. Technical
              health and performance are acceptable.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <span className="text-h2 tabular-nums text-foreground">64</span>
              <span className="text-sm text-muted-foreground">/ 100</span>
            </div>
            <div className="mt-2 h-2 rounded-full bg-surface-muted">
              <div
                className="h-2 rounded-full bg-[var(--severity-medium)]"
                style={{ width: "64%" }}
              />
            </div>
          </div>
        </section>

        {/* Category scores */}
        <section className="mt-12">
          <h2 className="text-h2 text-foreground">Category scores</h2>
          <div className="mt-6 space-y-3">
            {REPORT_SECTIONS.filter((s) => "score" in s).map((section) => {
              const s = section as {
                title: string;
                score: number;
                findings: number;
                status: string;
              };
              const scoreColor =
                s.score >= 80
                  ? "bg-[var(--success)]"
                  : s.score >= 60
                  ? "bg-[var(--severity-medium)]"
                  : s.score >= 40
                  ? "bg-[var(--severity-high)]"
                  : "bg-[var(--severity-critical)]";
              return (
                <div
                  key={s.title}
                  className="rounded-md border border-border bg-card p-4 shadow-xs"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-foreground">
                      {s.title}
                    </span>
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-muted-foreground">
                        {s.findings} findings
                      </span>
                      <span className="text-sm font-medium tabular-nums text-foreground">
                        {s.score}/100
                      </span>
                    </div>
                  </div>
                  <div className="mt-2 h-1.5 rounded-full bg-surface-muted">
                    <div
                      className={`h-1.5 rounded-full ${scoreColor}`}
                      style={{ width: `${s.score}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* Sample findings */}
        <section className="mt-12">
          <h2 className="text-h2 text-foreground">Sample findings</h2>
          <div className="mt-6 space-y-4">
            {SAMPLE_FINDINGS.map((finding) => {
              const severityColor =
                finding.severity === "High"
                  ? "bg-[var(--severity-high-bg)] text-[var(--severity-high-text)]"
                  : finding.severity === "Medium"
                  ? "bg-[var(--severity-medium-bg)] text-[var(--severity-medium-text)]"
                  : "bg-[var(--severity-low-bg)] text-[var(--severity-low-text)]";
              return (
                <div
                  key={finding.title}
                  className="rounded-lg border border-border bg-card p-5 shadow-xs"
                >
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-medium text-foreground">
                      {finding.title}
                    </h3>
                    <span
                      className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${severityColor}`}
                    >
                      {finding.severity}
                    </span>
                    <span className="text-xs text-muted-foreground">
                      {finding.category}
                    </span>
                  </div>
                  <div className="mt-3 space-y-1.5">
                    <div className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                      <span>
                        <strong className="text-foreground">Evidence:</strong>{" "}
                        {finding.evidence}
                      </span>
                    </div>
                    <div className="flex items-start gap-2 text-sm text-muted-foreground">
                      <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-border" />
                      <span>
                        <strong className="text-foreground">Impact:</strong>{" "}
                        {finding.impact}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* CTA */}
        <div className="mt-16 rounded-lg border border-border bg-primary-subtle p-8 text-center">
          <h2 className="text-h2 text-foreground">
            Explore the full product demo
          </h2>
          <p className="mt-3 text-body text-muted-foreground">
            The interactive demo includes the complete workflow from prospect to
            opportunity, with fictional data.
          </p>
          <div className="mt-6">
            <Button size="lg" asChild>
              <Link href="/app">
                Open demo
                <ArrowRight className="ml-1 size-4" />
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </SiteLayout>
  );
}
