"use client";

import { motion, useReducedMotion } from "framer-motion";
import {
  MonitorPlay,
  FileText,
  FileCheck,
  BookOpen,
  Boxes,
  Package,
  ShieldCheck,
  AlertTriangle,
  ScrollText,
  Rocket,
  History,
  Map,
} from "lucide-react";

/* ─── Inspection items ─── */
const INSPECTION_ITEMS = [
  {
    icon: MonitorPlay,
    label: "Read-only live demo",
    description: "Explore the full product in a sandboxed environment with sample data.",
    href: "#demo",
  },
  {
    icon: FileText,
    label: "Sample report",
    description: "Download a real client-facing audit report generated by WinterVell.",
    href: "#report",
  },
  {
    icon: FileCheck,
    label: "Sample proposal",
    description: "See how audit findings convert into a structured proposal document.",
    href: "#audit-to-proposal",
  },
  {
    icon: BookOpen,
    label: "Documentation preview",
    description: "Read the deployment guide, configuration reference, and API documentation.",
    href: "#architecture",
  },
  {
    icon: Boxes,
    label: "Architecture overview",
    description: "Understand the system design, data flow, and integration points.",
    href: "#architecture",
  },
  {
    icon: Package,
    label: "Dependency report",
    description: "Review every third-party dependency, its licence, and its purpose.",
    href: "#due-diligence",
  },
  {
    icon: ShieldCheck,
    label: "Security overview",
    description: "Examine the security model, SSRF protection, and access controls.",
    href: "#security",
  },
  {
    icon: AlertTriangle,
    label: "Known limitations",
    description: "See what WinterVell does not do — stated clearly, not hidden.",
    href: "#due-diligence",
  },
  {
    icon: ScrollText,
    label: "Licence preview",
    description: "Read the full commercial licence terms before you pay.",
    href: "#licence-comparison",
  },
  {
    icon: Rocket,
    label: "Deployment checklist",
    description: "Review the deployment requirements and infrastructure prerequisites.",
    href: "#ownership",
  },
  {
    icon: History,
    label: "Changelog",
    description: "Review version history, patch notes, and release cadence.",
    href: "#due-diligence",
  },
  {
    icon: Map,
    label: "Product roadmap",
    description: "See what is planned, what is in progress, and what is not planned.",
    href: "#due-diligence",
  },
] as const;

/* ─── Motion variants ─── */
const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.06 } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 16, scale: 0.97 },
  visible: { opacity: 1, y: 0, scale: 1, transition: { duration: 0.4, ease: "easeOut" } },
};

const headingVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

export default function BuyerRiskReduction() {
  const prefersReducedMotion = useReducedMotion();

  const sectionMotionProps = prefersReducedMotion
    ? { initial: false as const, animate: "visible" as const, variants: containerVariants }
    : { initial: "hidden" as const, whileInView: "visible" as const, viewport: { once: true, amount: 0.1 }, variants: containerVariants };

  return (
    <section id="buyer-risk" className="bg-[#F4F6F7]">
      <motion.div
        className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8 lg:py-36"
        {...sectionMotionProps}
      >
        {/* Heading */}
        <motion.div variants={headingVariants} className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight text-[#111820] sm:text-4xl">
            Inspect the product before you purchase it.
          </h2>
          <p className="mt-4 text-lg leading-relaxed text-[#56616C]">
            Every claim is verifiable. Explore the demo, review the documentation, and read the licence before you commit.
          </p>
        </motion.div>

        {/* Inspection grid */}
        <motion.div
          variants={containerVariants}
          className="mt-12 grid grid-cols-1 gap-4 sm:mt-16 sm:grid-cols-2 lg:grid-cols-3 sm:gap-5"
        >
          {INSPECTION_ITEMS.map((item) => {
            const Icon = item.icon;
            return (
              <motion.a
                key={item.label}
                href={item.href}
                variants={cardVariants}
                className="group flex items-start gap-4 rounded-xl border border-[#DDE3E7] bg-white p-5 shadow-sm transition-colors hover:border-[#2563EB]/30 hover:shadow-md"
              >
                <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-[#EFF8FC] transition-colors group-hover:bg-[#2563EB]/10">
                  <Icon className="size-5 text-[#2563EB]" aria-hidden="true" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold text-[#111820] group-hover:text-[#2563EB] transition-colors">
                    {item.label}
                  </p>
                  <p className="mt-1 text-xs leading-relaxed text-[#56616C]">
                    {item.description}
                  </p>
                </div>
              </motion.a>
            );
          })}
        </motion.div>

        {/* Integrity note */}
        <motion.div variants={headingVariants} className="mt-10">
          <div className="mx-auto max-w-2xl rounded-xl border border-[#B7791F]/30 bg-[#B7791F]/5 p-5 text-center">
            <div className="flex items-center justify-center gap-2">
              <AlertTriangle className="size-4 text-[#B7791F]" aria-hidden="true" />
              <p className="text-sm font-semibold text-[#B7791F]">
                Do not hide material limitations until after purchase.
              </p>
            </div>
            <p className="mt-2 text-xs leading-relaxed text-[#56616C]">
              Every known limitation, restriction, and boundary of WinterVell is documented in the
              due-diligence materials. If something is not listed, it is not a known limitation.
            </p>
          </div>
        </motion.div>
      </motion.div>
    </section>
  );
}
